services:
  nginx:
    container_name: nginx
    image: nginx:0.0.1
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - ./static:/usr/share/nginx/html
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: always
    ports:
        - 80:80
        - 443:443
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
